### ISSUE TITLE
TTS data preparation from News data

### ISSUE THREAD

**Issue by kaldan007** [OpenPecha/news-with-audio-data#1]
**Description**:
 We currently have news full audio and corresponding news transcript. We would like to get the news text and audio data split into segments to train our STT and TTS model.

**Implementation**:

**Subtask**:

- [x] update voa meta data with news reader name
- [x] delete the extra audio file
- [x] prepare catalog as per ganga suggestion
- [x] Spit audio into segments
- [x] Run inference in audio
- [x] Transfer news transcript

**Comment by kaldan007** [comment]
please run on two point catalog

**Comment by tenzinchoedon** [comment]
Sr. no 	ID 	Audio link	Audio text link	Audio Duration  (hh:mm:ss)	Speaker name	Speaker Gender	News channel	Publishing Year

**Comment by tenzinchoedon** [comment]
Link to the Google Sheet: https://docs.google.com/spreadsheets/d/1H1QVQgux6C170GSKKJ10wzNh0I-o1OL4BlWqe2BfViA/edit?gid=378785097#gid=378785097

**Comment by kaldan007** [comment]
@tenzinchoedon can u explore any existing lib to diff between male and female audio

**Comment by tenzinchoedon** [comment]
Here are some libraries used in python to classify the differences between male and female audio files:

### 1. **pyAudioAnalysis**
   - **Description**: A Python library that can analyze audio signals and extract various features. It supports gender classification for audio files.
   - **Usage**: You can extract features from audio, like pitch, frequency, etc., and apply a gender classifier. 
   - **Link**: [GitHub Repository](https://github.com/tyiannak/pyAudioAnalysis)

### 2. **Librosa**
   - **Description**: A Python library for analyzing and processing audio signals. It doesn't have built-in gender classification but can be used to extract features like pitch and formants, which can be input to a gender classifier.
   - **Usage**: You can extract features and then apply machine learning techniques for gender classification.
   - **Link**: [Librosa Documentation](https://librosa.org/doc/main/index.html)

### 3. **SpeechRecognition**
   - **Description**: A Python library for speech recognition that works with several engines, such as Google Web Speech API, Microsoft Bing Voice Recognition, etc. 
   - **Usage**: You can use this for transcription and then extract features from the transcription to differentiate gender.
   - **Link**: [SpeechRecognition Documentation](https://pypi.org/project/SpeechRecognition/)

**Comment by gangagyatso4364** [comment]
Analyzing the helpfulness of text transfer in new audio data.
Find the case of audio with news anchor and interviewee speaking. it should have 
1. News anchor audio text present in audio text file.
2. interviewee audio text not present in audio text file. 
3. Also compare the transfer text result before and after. 
4. Analyze how well text transfer works in comparison to audio book.

**Comment by kaldan007** [comment]
- [x] separate news with interview
- [x] get speaker name form voa and rfa
- [ ] run split audio pipeline on news without interview
